title: "Keagan Kozlowski's Github Page"
description: "Showcasing development projects and journey as a Computer Science student."
lsi: false
safe: true
source: Src/Main Page
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
